"""initial_schema

Revision ID: f384284cd4fb
Revises: 
Create Date: 2026-03-24 23:05:57.289024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f384284cd4fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_options', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('answer_options', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('answer_options', 'question_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('answer_options', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('categories', 'organization_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('uq_category_slug_org', table_name='categories')
    op.alter_column('courses', 'organization_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('courses', 'instructor_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('courses', 'category_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('courses', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('idx_courses_instructor', table_name='courses')
    op.drop_index('idx_courses_org', table_name='courses')
    op.drop_index('idx_courses_status', table_name='courses')
    op.drop_index('uq_course_slug_org', table_name='courses')
    op.create_index(op.f('ix_courses_instructor_id'), 'courses', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_courses_organization_id'), 'courses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    op.add_column('enrollments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('enrollments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('enrollments', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('enrollments', 'course_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('enrollments', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.add_column('learning_path_courses', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('learning_path_courses', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('learning_path_courses', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('learning_path_courses', 'learning_path_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('learning_path_courses', 'course_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.add_column('learning_paths', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('learning_paths', 'organization_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('learning_paths', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('uq_lp_slug_org', table_name='learning_paths')
    op.add_column('lesson_progress', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('lesson_progress', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('lesson_progress', 'enrollment_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'lesson_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'watch_time_sec',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('lesson_progress', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('lessons', 'course_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('lessons', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('lessons', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('idx_lessons_course', table_name='lessons')
    op.drop_index('idx_lessons_order', table_name='lessons')
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.alter_column('organizations', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('questions', 'quiz_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('questions', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.add_column('quiz_attempts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('quiz_attempts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('quiz_attempts', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'quiz_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('idx_attempts_user_quiz', table_name='quiz_attempts')
    op.create_unique_constraint('uq_quiz_attempt', 'quiz_attempts', ['user_id', 'quiz_id'])
    op.add_column('quizzes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('quizzes', 'course_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('quizzes', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'organization_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('idx_users_org', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('uq_user_email_org', table_name='users')
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.create_index('uq_user_email_org', 'users', ['email', 'organization_id'], unique=True)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_org', 'users', ['organization_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('users', 'organization_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('quizzes', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('quizzes', 'course_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('quizzes', 'updated_at')
    op.drop_constraint('uq_quiz_attempt', 'quiz_attempts', type_='unique')
    op.create_index('idx_attempts_user_quiz', 'quiz_attempts', ['user_id', 'quiz_id'], unique=False)
    op.alter_column('quiz_attempts', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'quiz_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('quiz_attempts', 'updated_at')
    op.drop_column('quiz_attempts', 'created_at')
    op.alter_column('questions', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.alter_column('organizations', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.create_index('idx_lessons_order', 'lessons', ['course_id', 'order_index'], unique=False)
    op.create_index('idx_lessons_course', 'lessons', ['course_id'], unique=False)
    op.alter_column('lessons', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('lessons', 'content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('lessons', 'course_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'watch_time_sec',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('lesson_progress', 'lesson_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'enrollment_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('lesson_progress', 'updated_at')
    op.drop_column('lesson_progress', 'created_at')
    op.create_index('uq_lp_slug_org', 'learning_paths', ['slug', 'organization_id'], unique=True)
    op.alter_column('learning_paths', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('learning_paths', 'organization_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('learning_paths', 'updated_at')
    op.alter_column('learning_path_courses', 'course_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('learning_path_courses', 'learning_path_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('learning_path_courses', 'updated_at')
    op.drop_column('learning_path_courses', 'created_at')
    op.drop_column('learning_path_courses', 'id')
    op.alter_column('enrollments', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('enrollments', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('enrollments', 'updated_at')
    op.drop_column('enrollments', 'created_at')
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_index(op.f('ix_courses_organization_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_instructor_id'), table_name='courses')
    op.create_index('uq_course_slug_org', 'courses', ['slug', 'organization_id'], unique=True)
    op.create_index('idx_courses_status', 'courses', ['status'], unique=False)
    op.create_index('idx_courses_org', 'courses', ['organization_id'], unique=False)
    op.create_index('idx_courses_instructor', 'courses', ['instructor_id'], unique=False)
    op.alter_column('courses', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('courses', 'category_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
    op.alter_column('courses', 'instructor_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('courses', 'organization_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_index('uq_category_slug_org', 'categories', ['slug', 'organization_id'], unique=True)
    op.alter_column('categories', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('categories', 'organization_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('categories', 'updated_at')
    op.alter_column('answer_options', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('answer_options', 'question_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('answer_options', 'updated_at')
    op.drop_column('answer_options', 'created_at')
    # ### end Alembic commands ###
